config/routes.rb
Rails.application.routes.draw do
  root 'home#author'
  get 'welcome/:first_name', to: 'welcome#first_name'
  get 'team_contact/team', to: 'team_contact#team'
  get 'team_contact/contact', to: 'team_contact#contact'
  get 'gossip_only/:id', to: 'gossip_only#methode'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_gossip_tags
    has_many :tag, through: :join_gossip_tags
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_gossip_tags
    has_many :gossips, through: :join_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city 
    has_many :gossip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_only_controller.rb
class GossipOnlyController < ApplicationController
    def methode
        @gossips = Gossip.all
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def author
    @gossips = Gossip.all
  end
end

app/controllers/team_contact_controller.rb
class TeamContactController < ApplicationController
  def team
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_only_helper.rb
module GossipOnlyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_contact_helper.rb
module TeamContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip_only/methode.html.erb
<h1>Gossip n°<%= params[:id] %> !</h1>

<p> <% gossip = Gossip.find(params[:id]) %></p>
<p> <%= user = User.find(gossip.user_id).first_name %></p>
<p> <%= gossip.title %></p>
<p> <%= gossip.content %></p>
<p> <%= gossip.created_at %></p>

app/views/home/author.html.erb
<h1>Bienvenue sur la page d'accueil !</h1>
  <p>
    <% @gossips.each do |gossip| %>
    <p> <%= gossip.title %></p>
    <p> <%= User.find(gossip.user_id).first_name %></p>
    <p> <%= link_to "Détails", "gossip_only/#{gossip.id}" %>
    <% end %>
  </p>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
      <%= link_to "Contact", team_contact_contact_path, class:"nav-link" %>
      </li>
      <li>
        <%= link_to "Team", team_contact_team_path, class:"nav-link" %>
      </li>
      <li>
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
    </ul>
   
  </div>
</nav>
  <div class="wrap">
    <%= yield %>
  </div>
  </body>
</html>

app/views/team_contact/contact.html.erb
<h1>TeamContact#contact</h1>
<p>Find me in app/views/team_contact/contact.html.erb</p>

app/views/team_contact/team.html.erb
<h1>TeamContact#team</h1>
<p>Find me in app/views/team_contact/team.html.erb</p>

app/views/welcome/first_name.html.erb
<h1>BIENVENUE <%= params[:first_name] %> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>
<p>Find me in app/views/welcome/first_name.html.erb</p>